plugins {
    id 'java'
    id 'application'
}

group = 'io.github.kaypes'
version = '1.0-SNAPSHOT'

application {
    // Aqui é onde a mágica acontece.
    // Você NÃO coloca o caminho do arquivo, mas sim o PACOTE + CLASSE
    mainClass = 'io.github.kaypes.Main' 
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'io.github.kaypes.Main'
}